from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from datetime import date
from typing import Dict, Iterable, List, Tuple


SECTION_ORDER = [
    "International Affairs",
    "Regional",
    "Pakistan (Local)",
    "Geopolitics & Power Shifts",
    "Economy & Technology",
]


def _plural(n: int, word: str) -> str:
    return f"{n} {word}" + ("" if n == 1 else "s")


def render_daily_brief_md(day: date, articles: Iterable[Dict]) -> str:
    by_cat: Dict[str, List[Dict]] = defaultdict(list)
    total = 0
    for a in articles:
        by_cat[a.get("category") or "International Affairs"].append(a)
        total += 1

    lines: List[str] = []
    lines.append(f"# Daily Intelligence Brief — {day.isoformat()}")
    lines.append("")
    lines.append(f"Total: {_plural(total, 'article')}")
    lines.append("")

    for section in SECTION_ORDER:
        items = by_cat.get(section, [])
        if not items:
            continue
        lines.append(f"## {section}")
        lines.append("")
        for art in items:
            title = art.get("title") or "(untitled)"
            url = art.get("url") or ""
            summary = (art.get("summary") or "").strip()
            lines.append(f"### {title}")
            lines.append(f"[Link]({url})")
            lines.append("")
            if summary:
                lines.append(summary)
                lines.append("")
        lines.append("")

    # Simple appendix with metadata
    lines.append("---")
    lines.append("_Generated by News Intelligence System_")
    lines.append("")
    return "\n".join(lines)

